version: "3"
services: 
    php:
        container_name: php-DAMP
        build: php
        ports: 
            - "{apache port on localhost}:80"
        volumes: 
            - ./php:/var/www/html
    mysql:
        image: mysql:8
        ports: 
            - "{mysql port on localhost}:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD={}
            - MYSQL_USER={}
            - MYSQL_PASSWORD={}
            - MYSQL_DATABASE={}
        volumes: 
            - ./mysql/data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin:5
        links: 
            - mysql
        restart: always
        ports: 
            - "{phpmyadmin port on localhost}:80"
        environment: 
            - PMA_HOST=mysql
    